-- Seed data: 30 realistic Bahamian citizen profiles
-- Run after migrate.sql

-- Clear existing data
TRUNCATE interest_areas, topic_votes, survey_responses, citizens RESTART IDENTITY CASCADE;

-- Citizens
INSERT INTO citizens (name, email, phone, lives_in_bahamas, island, country, age_group, sector) VALUES
('Deandra Rolle', 'deandra.rolle@gmail.com', '(242) 323-1001', true, 'New Providence (Nassau)', NULL, '25-34', 'Financial Services'),
('Marcus Thompson', 'marcus.t@outlook.com', '(242) 352-2002', true, 'Grand Bahama (Freeport)', NULL, '35-44', 'Tourism & Hospitality'),
('Shaniqua Johnson', 'shaniqua.j@yahoo.com', '(242) 367-3003', true, 'Abaco', NULL, '18-24', 'Student'),
('Ricardo Munroe', 'ricardo.munroe@bahamas.gov.bs', '(242) 323-4004', true, 'New Providence (Nassau)', NULL, '45-54', 'Government / Public Sector'),
('Tanya Williams', 'tanya.w@hotmail.com', '(242) 332-5005', true, 'Eleuthera', NULL, '55-64', 'Education'),
('Devon Smith', 'devon.smith@live.com', '(242) 345-6006', true, 'Exuma', NULL, '25-34', 'Technology / IT'),
('Crystal Bethel', 'crystal.b@gmail.com', '(242) 323-7007', true, 'New Providence (Nassau)', NULL, '18-24', 'Retail & Commerce'),
('Anthony Ferguson', 'a.ferguson@outlook.com', '(242) 368-8008', true, 'Andros', NULL, '35-44', 'Agriculture & Fisheries'),
('Jasmine Cartwright', 'jasmine.cart@yahoo.com', '(242) 323-9009', true, 'New Providence (Nassau)', NULL, '25-34', 'Healthcare'),
('Terrance Knowles', 'terrance.k@gmail.com', '(242) 352-1010', true, 'Grand Bahama (Freeport)', NULL, '45-54', 'Construction'),
('Monique Davis', 'monique.davis@hotmail.com', '(242) 337-1011', true, 'Long Island', NULL, '65+', 'Retired'),
('Patrick Sears', 'p.sears@gmail.com', '(242) 323-1012', true, 'New Providence (Nassau)', NULL, '35-44', 'Self-Employed / Entrepreneur'),
('Lakeisha Forbes', 'lakeisha.f@outlook.com', NULL, false, 'Cat Island', 'United States', '25-34', 'Tourism & Hospitality'),
('Dario Moss', 'dario.moss@yahoo.com', '(242) 323-1014', true, 'New Providence (Nassau)', NULL, '18-24', 'Technology / IT'),
('Renee Cooper', 'renee.cooper@gmail.com', '(242) 347-1015', true, 'San Salvador', NULL, '55-64', 'Government / Public Sector'),
('Carlton Strachan', 'carlton.s@live.com', NULL, false, 'Grand Bahama (Freeport)', 'Canada', '25-34', 'Financial Services'),
('Shantell Butler', 'shantell.b@gmail.com', '(242) 323-1017', true, 'New Providence (Nassau)', NULL, '35-44', 'Education'),
('Kendrick Bain', 'kendrick.bain@outlook.com', '(242) 346-1018', true, 'Bimini', NULL, '18-24', 'Tourism & Hospitality'),
('Angela Major', 'angela.m@yahoo.com', '(242) 323-1019', true, 'New Providence (Nassau)', NULL, '45-54', 'Healthcare'),
('Trevor Dean', 'trevor.dean@gmail.com', '(242) 339-1020', true, 'Inagua', NULL, '35-44', 'Government / Public Sector'),
('Nicole Lightbourne', 'nicole.l@hotmail.com', NULL, false, 'Grand Bahama (Freeport)', 'United Kingdom', '25-34', 'Retail & Commerce'),
('Jermaine Russell', 'jermaine.r@gmail.com', '(242) 323-1022', true, 'New Providence (Nassau)', NULL, '55-64', 'Construction'),
('Samantha Clarke', 'samantha.c@outlook.com', '(242) 335-1023', true, 'Acklins', NULL, '25-34', 'Agriculture & Fisheries'),
('Robert Adderley', 'robert.a@yahoo.com', '(242) 367-1024', true, 'Abaco', NULL, '45-54', 'Self-Employed / Entrepreneur'),
('Tamika Wells', 'tamika.w@gmail.com', NULL, false, 'New Providence (Nassau)', 'United States', '18-24', 'Student'),
('Dwight Rolle', 'dwight.rolle@live.com', '(242) 332-1026', true, 'Eleuthera', NULL, '35-44', 'Tourism & Hospitality'),
('Keisha McPhee', 'keisha.m@hotmail.com', '(242) 345-1027', true, 'Exuma', NULL, '65+', 'Retired'),
('Adrian Hepburn', 'adrian.h@gmail.com', '(242) 323-1028', true, 'New Providence (Nassau)', NULL, '25-34', 'Financial Services'),
('Sonia Armbrister', 'sonia.a@outlook.com', '(242) 348-1029', true, 'Berry Islands', NULL, '45-54', 'Education'),
('Desmond Curry', 'desmond.c@yahoo.com', '(242) 352-1030', true, 'Grand Bahama (Freeport)', NULL, '35-44', 'Technology / IT');

-- Survey Responses
INSERT INTO survey_responses (citizen_id, tech_comfort_level, primary_barrier, interested_in_careers, desired_skill, biggest_concern, best_opportunity, gov_tech_suggestion, preferred_gov_service) VALUES
(1, 4, 'Cost of internet / devices', true, 'Data analysis', 'The high cost of internet makes it hard for regular people to participate in the digital economy.', 'Fintech could revolutionize banking access across the islands.', 'Create a single government portal for all services.', 'Online tax filing'),
(2, 3, 'Lack of training or skills', false, 'Digital marketing', 'Tourism industry needs better tech integration but workers lack training.', 'Digital tourism marketing could attract more visitors to Family Islands.', 'Better online booking systems for government-related tourism permits.', 'Business registration online'),
(3, 5, 'Cost of internet / devices', true, 'Coding / Software development', 'My generation wants tech careers but there are few opportunities in Nassau.', 'Young Bahamians could build apps and services for the Caribbean region.', 'Offer free Wi-Fi in all government buildings and public spaces.', 'Online education portal'),
(4, 3, 'Privacy / security concerns', false, 'Cybersecurity', 'Government systems are vulnerable to cyber attacks and data breaches.', 'Digitizing government services would reduce corruption and increase transparency.', 'Invest in cybersecurity training for all government employees.', 'Digital ID / passport renewal'),
(5, 2, 'Lack of training or skills', false, 'Basic computer literacy', 'Many teachers still do not know how to use technology effectively in classrooms.', 'Online learning could reach students on remote islands who lack resources.', 'Provide tablets and internet access to every school in the country.', 'Online education portal'),
(6, 5, 'Limited internet access in my area', true, 'AI / Machine learning', 'Brain drain - our best tech talent leaves for the US because there are no jobs here.', 'The Bahamas could become a Caribbean tech hub if we invest in infrastructure.', 'Build a government tech incubator and offer tax breaks for tech startups.', 'Business registration online'),
(7, 3, 'Cost of internet / devices', false, 'Digital marketing', 'Small businesses cannot afford the technology they need to compete.', 'E-commerce could open up Family Island businesses to the world.', 'Create small business tech grants and subsidize internet costs.', 'Online utility payments'),
(8, 2, 'Limited internet access in my area', false, 'Basic computer literacy', 'Andros has terrible internet coverage. We feel left behind.', 'Technology could help farmers track weather patterns and market prices.', 'Extend broadband to all inhabited islands, not just Nassau and Freeport.', 'Online utility payments'),
(9, 4, 'Privacy / security concerns', true, 'Data analysis', 'Patient data security is a major concern as we digitize health records.', 'Telemedicine could transform healthcare access for Family Island residents.', 'Implement a national electronic health records system with proper security.', 'E-health records'),
(10, 2, 'Lack of training or skills', false, 'Project management', 'Construction industry is behind on adopting modern technology.', 'Building Information Modeling could reduce costs and improve project delivery.', 'Require digital building permits and inspection reports.', 'Digital land registry'),
(11, 1, 'Don''t see the need', false, 'Basic computer literacy', 'Technology moves too fast for people my age. We get left behind.', 'Video calls let me stay connected with grandchildren in Nassau.', 'Offer free computer classes for seniors at community centers.', 'Digital ID / passport renewal'),
(12, 4, 'Cost of internet / devices', true, 'Graphic design', 'Starting a business in the Bahamas requires too much paperwork and in-person visits.', 'Digital tools let small businesses punch above their weight in global markets.', 'All business registration and licensing should be 100% online.', 'Business registration online'),
(13, 3, 'Limited internet access in my area', false, 'Digital marketing', 'Cat Island tourists want to book online but our internet is unreliable.', 'Family Islands could develop eco-tourism through better online presence.', 'Install community Wi-Fi hotspots in all settlement centers.', 'Government job portal'),
(14, 5, 'Cost of internet / devices', true, 'Coding / Software development', 'We need more hackathons and coding competitions to build a tech culture.', 'Bahamian developers could create solutions for Caribbean-specific problems.', 'Partner with tech companies to create internship programs for young Bahamians.', 'Online education portal'),
(15, 2, 'Lack of local tech support', false, 'Cybersecurity', 'Government websites go down frequently and are hard to navigate.', 'E-government could save people from traveling to Nassau for every document.', 'Hire competent IT professionals and pay them competitive salaries.', 'Online court services'),
(16, 4, 'Cost of internet / devices', true, 'AI / Machine learning', 'Banking fees are too high and technology could help bring them down.', 'Digital banking and crypto could provide financial inclusion for the unbanked.', 'Support the Sand Dollar digital currency and reduce transaction fees.', 'Online tax filing'),
(17, 3, 'Lack of training or skills', false, 'Project management', 'Teachers need ongoing professional development in technology.', 'Blended learning models could improve education outcomes across the islands.', 'Create a national teacher training program for educational technology.', 'Online education portal'),
(18, 4, 'Cost of internet / devices', true, 'Digital marketing', 'Young people in Bimini have to leave for better opportunities.', 'Marine technology and tourism tech could create jobs on smaller islands.', 'Create a youth tech apprenticeship program.', 'Government job portal'),
(19, 3, 'Privacy / security concerns', false, 'Cybersecurity', 'Hospital record systems are outdated and error-prone.', 'AI diagnostics could help our understaffed clinics serve patients better.', 'Implement telemedicine for Family Island clinics.', 'E-health records'),
(20, 2, 'Limited internet access in my area', false, 'Basic computer literacy', 'Inagua has the worst connectivity in the country. We need help.', 'Technology could help environmental monitoring and conservation efforts.', 'The government must treat internet as a basic utility.', 'Emergency alert system'),
(21, 4, 'Cost of internet / devices', false, 'Digital marketing', 'Cost of living in Freeport makes it hard to invest in technology.', 'Grand Bahama could attract remote workers with better infrastructure.', 'Reduce import duties on computers and tech equipment.', 'Online utility payments'),
(22, 2, 'Lack of training or skills', false, 'Project management', 'Many tradespeople could benefit from technology but nobody teaches us.', 'Construction tech could create safer building practices in hurricane zones.', 'Offer trade-specific technology courses at BTVI.', 'Digital land registry'),
(23, 3, 'Limited internet access in my area', false, 'Data analysis', 'Farming in Acklins is still done the old way. Technology could help.', 'Agricultural technology could help food security and reduce imports.', 'Create a national agricultural technology program.', 'Business registration online'),
(24, 4, 'Lack of local tech support', true, 'Graphic design', 'When something breaks there is nobody qualified to fix it on the outer islands.', 'Abaco could attract tech workers looking for island lifestyle.', 'Train local technicians on every major island.', 'Business registration online'),
(25, 5, 'Cost of internet / devices', true, 'Coding / Software development', 'I want to study computer science but COB barely offers courses.', 'Bahamian youth could lead tech innovation in the Caribbean.', 'Offer coding boot camps and scholarships for tech education.', 'Online education portal'),
(26, 3, 'Limited internet access in my area', false, 'Digital marketing', 'Eleuthera tourism could boom with better online marketing tools.', 'Sustainable tourism tech could be a model for the Caribbean.', 'Build out fiber optic connections to all major Family Islands.', 'Online utility payments'),
(27, 1, 'Lack of training or skills', false, 'Basic computer literacy', 'At my age, even using a smartphone is challenging.', 'Keeping in touch with family through technology is wonderful.', 'Have patient young people teach seniors at churches and community centers.', 'Digital ID / passport renewal'),
(28, 4, 'Cost of internet / devices', true, 'Data analysis', 'Financial services sector needs to modernize or lose business to other jurisdictions.', 'The Bahamas could lead Caribbean fintech innovation.', 'Create regulatory sandbox for fintech startups.', 'Online tax filing'),
(29, 3, 'Lack of training or skills', false, 'Project management', 'Berry Islands schools need better technology resources.', 'Distance learning could equalize education between Nassau and Family Islands.', 'Every school should have reliable internet and modern computers.', 'Online education portal'),
(30, 5, 'Cost of internet / devices', true, 'AI / Machine learning', 'Internet costs in the Bahamas are among the highest in the Caribbean.', 'The Bahamas could become a Caribbean AI research and development center.', 'Regulate internet providers to bring down costs and improve service.', 'Business registration online');

-- Topic Votes (3 per citizen)
INSERT INTO topic_votes (citizen_id, topic, rank) VALUES
(1, 'Digital financial inclusion', 1), (1, 'Affordable internet access', 2), (1, 'Support for local tech startups', 3),
(2, 'Tech education in schools', 1), (2, 'E-commerce development', 2), (2, 'Digital government services', 3),
(3, 'Support for local tech startups', 1), (3, 'Affordable internet access', 2), (3, 'Tech education in schools', 3),
(4, 'Cybersecurity and data privacy', 1), (4, 'Digital government services', 2), (4, 'Smart city infrastructure', 3),
(5, 'Tech education in schools', 1), (5, 'Affordable internet access', 2), (5, 'Telemedicine and e-health', 3),
(6, 'Support for local tech startups', 1), (6, 'Affordable internet access', 2), (6, 'Smart city infrastructure', 3),
(7, 'E-commerce development', 1), (7, 'Affordable internet access', 2), (7, 'Support for local tech startups', 3),
(8, 'Affordable internet access', 1), (8, 'Environmental tech solutions', 2), (8, 'Tech education in schools', 3),
(9, 'Telemedicine and e-health', 1), (9, 'Cybersecurity and data privacy', 2), (9, 'Digital government services', 3),
(10, 'Smart city infrastructure', 1), (10, 'Tech education in schools', 2), (10, 'Digital government services', 3),
(11, 'Digital government services', 1), (11, 'Telemedicine and e-health', 2), (11, 'Affordable internet access', 3),
(12, 'E-commerce development', 1), (12, 'Support for local tech startups', 2), (12, 'Digital government services', 3),
(13, 'Affordable internet access', 1), (13, 'E-commerce development', 2), (13, 'Tech education in schools', 3),
(14, 'Support for local tech startups', 1), (14, 'Tech education in schools', 2), (14, 'Affordable internet access', 3),
(15, 'Digital government services', 1), (15, 'Cybersecurity and data privacy', 2), (15, 'Smart city infrastructure', 3),
(16, 'Digital financial inclusion', 1), (16, 'Support for local tech startups', 2), (16, 'Affordable internet access', 3),
(17, 'Tech education in schools', 1), (17, 'Digital government services', 2), (17, 'Affordable internet access', 3),
(18, 'Support for local tech startups', 1), (18, 'Affordable internet access', 2), (18, 'E-commerce development', 3),
(19, 'Telemedicine and e-health', 1), (19, 'Cybersecurity and data privacy', 2), (19, 'Tech education in schools', 3),
(20, 'Affordable internet access', 1), (20, 'Environmental tech solutions', 2), (20, 'Digital government services', 3),
(21, 'Affordable internet access', 1), (21, 'E-commerce development', 2), (21, 'Smart city infrastructure', 3),
(22, 'Tech education in schools', 1), (22, 'Smart city infrastructure', 2), (22, 'Affordable internet access', 3),
(23, 'Environmental tech solutions', 1), (23, 'Affordable internet access', 2), (23, 'Tech education in schools', 3),
(24, 'Support for local tech startups', 1), (24, 'Affordable internet access', 2), (24, 'E-commerce development', 3),
(25, 'Tech education in schools', 1), (25, 'Support for local tech startups', 2), (25, 'Affordable internet access', 3),
(26, 'Affordable internet access', 1), (26, 'E-commerce development', 2), (26, 'Environmental tech solutions', 3),
(27, 'Digital government services', 1), (27, 'Telemedicine and e-health', 2), (27, 'Tech education in schools', 3),
(28, 'Digital financial inclusion', 1), (28, 'Support for local tech startups', 2), (28, 'Cybersecurity and data privacy', 3),
(29, 'Tech education in schools', 1), (29, 'Affordable internet access', 2), (29, 'Digital government services', 3),
(30, 'Affordable internet access', 1), (30, 'Support for local tech startups', 2), (30, 'Smart city infrastructure', 3);

-- Interest Areas
INSERT INTO interest_areas (citizen_id, area) VALUES
(1, 'Tech career mentorship'), (1, 'Small business tech grants'),
(2, 'Free coding workshops'), (2, 'Senior digital literacy classes'),
(3, 'Free coding workshops'), (3, 'Hackathons and competitions'), (3, 'Tech internship programs'),
(4, 'Open data initiatives'), (4, 'Tech career mentorship'),
(5, 'Senior digital literacy classes'), (5, 'Youth tech programs'),
(6, 'Hackathons and competitions'), (6, 'Tech internship programs'), (6, 'Small business tech grants'),
(7, 'Small business tech grants'), (7, 'Free coding workshops'),
(8, 'Community Wi-Fi hotspots'), (8, 'Senior digital literacy classes'),
(9, 'Tech career mentorship'), (9, 'Women in tech initiatives'),
(10, 'Free coding workshops'), (10, 'Community Wi-Fi hotspots'),
(11, 'Senior digital literacy classes'), (11, 'Community Wi-Fi hotspots'),
(12, 'Small business tech grants'), (12, 'Hackathons and competitions'), (12, 'Tech career mentorship'),
(13, 'Community Wi-Fi hotspots'), (13, 'Small business tech grants'),
(14, 'Hackathons and competitions'), (14, 'Tech internship programs'), (14, 'Free coding workshops'),
(15, 'Open data initiatives'),
(16, 'Tech career mentorship'), (16, 'Small business tech grants'), (16, 'Hackathons and competitions'),
(17, 'Youth tech programs'), (17, 'Free coding workshops'),
(18, 'Youth tech programs'), (18, 'Tech internship programs'), (18, 'Free coding workshops'),
(19, 'Women in tech initiatives'), (19, 'Tech career mentorship'),
(20, 'Community Wi-Fi hotspots'),
(21, 'Small business tech grants'), (21, 'Free coding workshops'),
(22, 'Free coding workshops'), (22, 'Community Wi-Fi hotspots'),
(23, 'Community Wi-Fi hotspots'), (23, 'Small business tech grants'),
(24, 'Small business tech grants'), (24, 'Tech career mentorship'),
(25, 'Hackathons and competitions'), (25, 'Tech internship programs'), (25, 'Free coding workshops'), (25, 'Youth tech programs'),
(26, 'Community Wi-Fi hotspots'), (26, 'Small business tech grants'),
(27, 'Senior digital literacy classes'),
(28, 'Tech career mentorship'), (28, 'Hackathons and competitions'),
(29, 'Youth tech programs'), (29, 'Community Wi-Fi hotspots'),
(30, 'Hackathons and competitions'), (30, 'Tech internship programs'), (30, 'Small business tech grants');
